# Generated by Django 3.2.9 on 2023-03-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        ('users', '0002_auto_20230322_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.apartments'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.rooms', verbose_name='Rented Room'),
        ),
    ]
