# Generated by Django 3.2.9 on 2023-03-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_rooms_tenant'),
        ('users', '0005_auto_20230322_2046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('name', 'room')},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='apartment',
        ),
    ]
