# Generated by Django 3.2.9 on 2023-03-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_rooms_tenant'),
        ('users', '0006_auto_20230322_2358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('room', 'name')},
        ),
    ]
