# Generated by Django 3.2.9 on 2023-03-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_rooms_tenant'),
        ('users', '0010_alter_userprofile_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('room', 'room')},
        ),
    ]
