# Generated by Django 3.2.9 on 2023-03-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_rooms_tenant'),
        ('users', '0013_auto_20230323_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.apartments'),
        ),
    ]
