# Generated by Django 3.2.9 on 2023-03-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userprofile_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
