# Generated by Django 3.2.9 on 2023-03-23 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_rooms_tenant'),
        ('users', '0018_auto_20230323_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.apartments'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.rooms', verbose_name='Rented Room'),
        ),
    ]
