# Generated by Django 3.2.9 on 2023-03-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_rooms_tenant'),
        ('users', '0022_alter_userprofile_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('room',)},
        ),
    ]
