# Generated by Django 4.1.7 on 2023-03-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Apartments',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Header',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(max_length=55, null=True)),
                ('rent', models.PositiveBigIntegerField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('house_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.category')),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.PositiveBigIntegerField(null=True, unique=True, verbose_name='Room Number')),
                ('floor', models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('First Floor', 'First Floor'), ('Second Floor', 'Second Floor'), ('Third Floor', 'Third Floor'), ('Fourth Floor', 'Fourth Floor'), ('Fifth Floor', 'Fifth Floor'), ('sixth Floor', 'sixth Floor'), ('Eighth Floor', 'Eighth Floor'), ('Nineth Floor', 'Nineth Floor'), ('Tenth Floor', 'Tenth Floor')], max_length=50, null=True)),
                ('price', models.IntegerField()),
                ('house_description', models.TextField(blank=True, null=True, verbose_name='Room Description')),
                ('image1', models.ImageField(default='empty.jpg', upload_to='')),
                ('image2', models.ImageField(default='empty.jpg', upload_to='')),
                ('image3', models.ImageField(default='empty.jpg', upload_to='')),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Currently Occupied', 'Currently Occupied'), ('Ready To Move In', 'Ready To Move In'), ('Under Maintanance', 'Under Maintanance')], default='Ready To Move In', max_length=20)),
                ('maintainance', models.CharField(choices=[('Under Maintainance', 'Under Maintainance'), ('In Good Condition', 'In Good Condition')], default='In Good Condition', max_length=20)),
                ('booked', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.apartments')),
                ('house_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.category', verbose_name='Room Category')),
            ],
            options={
                'verbose_name_plural': 'Houses',
            },
        ),
    ]
