# Generated by Django 3.2.9 on 2023-03-22 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230322_1952'),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
