# Generated by Django 3.2.9 on 2023-03-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_rooms_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='tenant',
        ),
    ]
