# Generated by Django 3.2.9 on 2023-03-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_apartments_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rooms',
            unique_together={('apartment', 'house_number')},
        ),
    ]
