# Generated by Django 3.2.9 on 2023-03-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_rooms_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='house_number',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Room Number'),
        ),
    ]
