# Generated by Django 3.2.9 on 2023-03-13 09:23

from django.db import migrations, models
import houses.models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_rooms_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='image1',
            field=models.ImageField(default='empty.jpg', upload_to='', ),
        ),
    ]
