# Generated by Django 3.2.9 on 2023-03-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_rooms_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='house_number',
            field=models.PositiveBigIntegerField(null=True, unique=True, verbose_name='Room Number'),
        ),
    ]
