# Generated by Django 3.2.9 on 2023-03-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_alter_rooms_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='house_number',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Room Number'),
        ),
    ]
