# Generated by Django 3.2.9 on 2023-04-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentpayments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualrentpayments',
            options={'verbose_name_plural': 'Manual Rent Payments'},
        ),
    ]
