# Generated by Django 3.2.9 on 2023-03-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentpayments', '0003_auto_20230324_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentpayments',
            name='error_message',
        ),
    ]
