# Generated by Django 3.2.9 on 2023-04-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentpayments', '0004_auto_20230414_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesaonlinepayments',
            name='update_status',
        ),
        migrations.AddField(
            model_name='mpesaonlinepayments',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
    ]
