# Generated by Django 3.2.9 on 2023-04-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentpayments', '0008_remove_rentpayments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayments',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='Pending', max_length=15),
        ),
    ]
