# Generated by Django 3.2.9 on 2023-04-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('rentpayments', '0012_remove_rentpayments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdetails',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
