# Generated by Django 3.2.9 on 2023-04-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentpayments', '0013_rentdetails_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentdetails',
            name='tenant',
        ),
    ]
