# Generated by Django 3.2.9 on 2023-04-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentpayments', '0014_remove_rentdetails_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentdetails',
            name='cleared',
        ),
    ]
