# Generated by Django 3.2.9 on 2023-04-16 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('houses', '0001_initial'),
        ('rentpayments', '0016_auto_20230415_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRentPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateField(auto_created=True, blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rent_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentpayments.rentdetails')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.rooms')),
                ('tenant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
