# Generated by Django 3.2.9 on 2023-04-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('rentpayments', '0018_auto_20230416_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantrentpayments',
            options={'verbose_name': 'Tenant Rent Payments', 'verbose_name_plural': 'Tenant Rent Payments'},
        ),
        migrations.AlterUniqueTogether(
            name='tenantrentpayments',
            unique_together={('tenant', 'rent_details')},
        ),
    ]
