# Generated by Django 3.2.9 on 2023-04-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentpayments', '0019_auto_20230416_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantrentpayments',
            name='updated',
        ),
    ]
