# Generated by Django 3.2.9 on 2023-03-22 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='your Username'),
        ),
        migrations.AddField(
            model_name='allocateroom',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.rooms'),
        ),
        migrations.AddField(
            model_name='allocateroom',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='allocateroom',
            unique_together={('tenant', 'room')},
        ),
    ]
