# Generated by Django 3.2.9 on 2023-03-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocateroom',
            name='allocate_date',
        ),
        migrations.AddField(
            model_name='allocateroom',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
