# Generated by Django 3.2.9 on 2023-03-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230323_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocateroom',
            old_name='date',
            new_name='disalloacate_date',
        ),
    ]
