# Generated by Django 3.2.9 on 2023-03-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_noticestotenants_notice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='other',
            new_name='subject',
        ),
    ]
