# Generated by Django 3.2.9 on 2023-03-13 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_rename_other_complaints_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='room',
        ),
        migrations.AlterField(
            model_name='complaints',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='your Username'),
        ),
    ]
