# Generated by Django 3.2.9 on 2023-03-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_date_allocateroom_disalloacate_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allocateroom',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='allocateroom',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='allocateroom',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='allocateroom',
            name='room',
        ),
    ]
