# Generated by Django 3.2.9 on 2023-03-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_rooms_tenant'),
        ('dashboard', '0005_auto_20230323_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocateroom',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.rooms'),
        ),
    ]
