# Generated by Django 3.2.9 on 2023-03-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_complaints_reported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='created',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
