# Generated by Django 3.2.9 on 2023-03-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_rooms_tenant'),
        ('users', '0016_auto_20230323_0733'),
        ('dashboard', '0007_rename_disalloacate_date_allocateroom_alloacate_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocateroom',
            old_name='alloacate_date',
            new_name='allocate_date',
        ),
        migrations.AddField(
            model_name='allocateroom',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='allocateroom',
            name='paid',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='allocateroom',
            unique_together={('tenant', 'room')},
        ),
    ]
